apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: kctf
spec:
  deployed: true
  powDifficultySeconds: 1
  network:
    public: true
  healthcheck:
    enabled: true
    image: eu.gcr.io/gctf-vrp/kctf-healthcheck:ba3b7b5b6e67d1cf29e43748113a4ad7f9b5c81f5c2e22e28cd0d093cf2d4cde
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: flag
                mountPath: /flag
                readOnly: true
              - name: image
                mountPath: /etc/node-image
                readOnly: true
              - name: boot
                mountPath: /node-boot
                readOnly: true
              - name: etc-os-release
                mountPath: /etc/node-os-release
                readOnly: true
        volumes:
          - name: etc-os-release
            hostPath:
              path: /etc/os-release
          - name: boot
            hostPath:
              path: /boot
          - name: image
            secret:
              defaultMode: 0555
              secretName: node-image
              optional: true
          - name: flag
            secret:
              defaultMode: 0555
              secretName: kctf-flag
              optional: true
  image: eu.gcr.io/gctf-vrp/kctf-challenge:d9e48607036aaf10d3c59bb111dc3c62e7b96e72c5773e00d6b6a40f836d6155
